### ISSUE TITLE
DEX aggregate front end 

### ISSUE THREAD

**Issue by fjeffkirk** [crunchy-network/crunchy-dapp#13]
@MelvinManni here is the design for the dex aggregate: https://www.figma.com/file/hQKpaGwWFClpLRejn9iI98/Crypto-Projects?node-id=3138%3A2725

The idea is you can swap between one token to another. The benefit of a dex aggregate is it pulls trading data from other dex's to guarantee you get the best rate without visiting every dex.

Remember to keep everything within the framework of Crunchy and if you have any questions just let me know.

**Comment by touhonoob** [comment]
Is this feature gonna depend on an on-chain contract router or it's gonna be purely frtonend based like https://github.com/keshan3262/swap-router-sdk ?
